// ./src/apis/user/domain/service/user.domain.service.ts
// This file is generated by a shell script.

export class UserDomainService {
    exampleDomainServiceFunc() {
        return 'exampleDomainServiceFunc';
    }
}
