export const WINSTON_MODLUE_PROVIDER = Symbol('WINSTON_MODLUE_PROVIDER');
export const WINSTON_MODULE_NEST_PROVIDER = Symbol('WINSTON_MODULE_NEST_PROVIDER');
export const WINSTON_MODULE_OPTIONS = Symbol('WINSTON_MODULE_OPTIONS');
