// ./src/apis/user/adaptor/in/user.controller.ts
// This file is generated by a shell script.
import { Controller } from '@nestjs/common';
import { iUserUseCase } from '../../application/port/in/user.usecase';

@Controller('/user')
export class UserController {
    constructor(private readonly userService: iUserUseCase) {}
}
