// ./src/apis/user/user.module.ts
// This file is generated by a shell script.
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { iUserRepositoryPort } from './application/port/out/user.repository.port';
import { UserRepository } from './adaptor/out/user.repository';
import { iUserUseCase } from './application/port/in/user.usecase';
import { UserApplicationService } from './application/service/user.application.service';
import { UserDomainService } from './domain/service/user.domain.service';
import { UserController } from './adaptor/in/user.controller';

@Module({
    imports: [TypeOrmModule.forFeature([ExampleEntity])],
    controllers: [UserController],
    providers: [
        { provide: iUserRepositoryPort, useClass: UserRepository },
        { provide: iUserUseCase, useClass: UserApplicationService },
        { provide: UserDomainService, useClass: UserDomainService },
    ],
})
export class UserModule {}
